import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
env_path = Path(__file__).parent / '.env'
if env_path.exists():
    load_dotenv(env_path)

# AWS Configuration — all values come from .env (generated by deploy.sh)
AWS_REGION = os.getenv('AWS_REGION', 'us-east-1')
ATHENA_DATABASE = os.getenv('ATHENA_DATABASE', '')
ATHENA_OUTPUT_BUCKET = os.getenv('ATHENA_OUTPUT_BUCKET', '')
GLUE_TABLE_NAME = os.getenv('GLUE_TABLE_NAME', '')
IDENTITY_STORE_ID = os.getenv('IDENTITY_STORE_ID', '')

# Prompt Logging Configuration
# S3 bucket/prefix where Kiro prompt logs are stored (e.g. s3://my-bucket/kiro-prompt-logs/)
PROMPT_LOG_S3_URI = os.getenv('PROMPT_LOG_S3_URI', '')

# Streamlit Configuration
PAGE_TITLE = "Kiro Users Report"
PAGE_ICON = "⚡"
LAYOUT = "wide"
